meta_product_name: "Zookeeper"
meta_title: "Zookeeper - Location Espace Ephémère Paris"
meta_description: "Location Espace Ephémère Paris – Privatisation d’Espace
      Paris PopUpStore 40m2 situé dans le Haut-Marais. location à la journée, semaine ou au mois !"
meta_image: "photo-boutique2.jpg" # should exist in `app/assets/images/`
